### ISSUE TITLE
Rhino does not reflect objects were selected

### ISSUE THREAD

**Issue by locivir** [mcneel/rhinocommon#144]
I have a problem with selecting objects. I'm writing a c# plugin with an adjusted layer panel. The selection of object works through Rhinocommon, but in Rhino the Gumball does not get updated after selecting items. Also, if I'm in a command which requires selection of objects (e.g. BooleanDifference), it does not "see" that new object were selected. When I select multiple objects like this and add another object to the selection (or with shift select an selected object again) rhino acts normally. The gumball shows up and running command takes the selection.

Below is the function to select objects on a specific layer.

private void ActionSelectAddObjects(object sender)
{
    // Get the layer that got clicked upon
    Layer l = LocivirRhinoLayerPanel_GetLayer(sender);
    // Do nothing if we could not get the layer
    if (l == null) return;
    // Get all objects on the layer
    Rhino.DocObjects.RhinoObject[] objs = RhinoDoc.ActiveDoc.Objects.FindByLayer(l);
    // If [Control] is pressed, unselect all object before selecting new objects
    if (Control.ModifierKeys == Keys.Control) RhinoDoc.ActiveDoc.Objects.UnselectAll();
// Check if there we got any objects returned
    if (objs != null)
    {
        // Rotate through the objects and select them if they are selectable
        foreach (RhinoObject obj in objs)
            RhinoDoc.ActiveDoc.Objects.Select(obj.Id, true);
    }
    // Reflect the selection changes in the viewports
    RhinoDoc.ActiveDoc.Views.Redraw();
    // Reset the focus to the main window
    RhinoApp.SetFocusToMainWindow();
}

**Comment by marcsyp** [comment]
Incidentally, I had the same issue recently in a C# component inside grasshopper, and Ernst's workaround worked while Dale your code didn't.  Is there a better way to approach it in Grasshopper?

Cheers,
Marc

**Comment by dalefugier** [comment]
Hey @marcsyp, the two code samples call the same underlying C++ code. If you have something that isn't working for you, feel free to send your code my way.

-- Dale
