### ISSUE TITLE
ObjectTable replace with Extrusion

### ISSUE THREAD

**Issue by jmirtsch** [mcneel/rhinocommon#152]
Hi, The ObjectTable.Replace method doesn't have an overload for an extrusion.  When I execute it with an extrusion, it seems to get cast back to a surface and this is the object placed in the Rhino document.  Could the overload be added please?

Thanks,

Jon

**Comment by dalefugier** [comment]
Rhino 6 has this: http://developer.rhino3d.com/api/RhinoCommon/html/M_Rhino_DocObjects_Tables_ObjectTable_Replace_31.htm
