### ISSUE TITLE
Wish RhinoOffsetSurface Function

### ISSUE THREAD

**Issue by huaxiamengqing** [mcneel/rhinocommon#158]
Wish function about 
RHINO_SDK_FUNCTION ON_Brep\* RhinoOffsetSurface(const ON_BrepFace& face, const double dOffsetDistance, const double dTolerance = 0.0, const bool bBothSides = false, const bool bSolid = false, double\* pAchievedTol = 0);
in rhinocommon.

**Comment by pearswj** [comment]
See [Brep_CreateFromOffsetFace()](http://developer.rhino3d.com/api/RhinoCommon/html/M_Rhino_Geometry_Brep_CreateFromOffsetFace.htm)
