### ISSUE TITLE
BrepEdge accessing Vertex index

### ISSUE THREAD

**Issue by jmirtsch** [mcneel/rhinocommon#165]
Hi, 

Apologies if I've missed something, but seems that I can access start/end vertex index from a BrepEdge in RhinoCommon as I could in the old dotnet class.

Thanks,

Jon

**Comment by pearswj** [comment]
Hey @jmirtsch, we're going through and clearing up these old issues...

In case anyone comes across this is the future, you can use the [BrepVertex.VertexIndex](http://developer.rhino3d.com/api/RhinoCommon/html/P_Rhino_Geometry_BrepVertex_VertexIndex.htm) property on the BrepVertex that is returned by either [BrepEdge.StartVertex](http://developer.rhino3d.com/api/RhinoCommon/html/P_Rhino_Geometry_BrepEdge_StartVertex.htm) or [BrepEdge.EndVertex](http://developer.rhino3d.com/api/RhinoCommon/html/P_Rhino_Geometry_BrepEdge_EndVertex.htm).
