### ISSUE TITLE
_CurveBoolean  RhinoCommand to Rhinocommon

### ISSUE THREAD

**Issue by huaxiamengqing** [mcneel/rhinocommon#166]
Hi Sbaer,I wish _CurveBoolean command in Rhino Can be add to Rhinocommon SDK.
Thank you!

**Comment by pearswj** [comment]
See [Rhino.Geometry.Curve.CreateBooleanUnion()](http://developer.rhino3d.com/api/RhinoCommon/html/Overload_Rhino_Geometry_Curve_CreateBooleanUnion.htm)
