### ISSUE TITLE
RhinoDoc.EndSaveDocument fires before document is saved

### ISSUE THREAD

**Issue by rosecodym** [mcneel/rhinocommon#168]
When a document is saved with the Save command, the RhinoDoc.OnEndSaveDocument command will fire before the document is saved. The behavior is reproduced by a plugin at https://www.dropbox.com/s/fxz6dhtmhn1jmk1/MisorderedSaveEvents.zip?dl=0 . This has been tested against the RhinoCommon library shipping with SR11 on Windows 7.

**Comment by dalefugier** [comment]
I'm not sure what you are seeing in the output of your test command that makes you believe this. But I can assure you this isn't the case, just having looked at Rhino's I/O code.

If you want to discuss this further, please create a new thread on our Discourse discussion forum so others can benefit from our conversation.

http://discourse.mcneel.com/c/rhino-developer

-- Dale
