### ISSUE TITLE
[WISH] Consolidate Rhino.Geometry.Curve and Rhino.Geometry.Arc similar methods/attributes.

### ISSUE THREAD

**Issue by angellinares** [mcneel/rhinocommon#169]
Hi!,

First of all, thanks for your great job with the API. I'm dealing almost everyday with it and it's a piece of cake compared to other APIs, libraries, etc I've ever used.

I've noticed that similar methods/attributes for Arc and Curve objects are different but they do exactly the same. I don't know if this could be solved making that Arc class inherits some of those properties from the class Curve. For instance it is very annoying to have to remember that for requesting Arc endpoints you have to use Arc.EndPoint and Arc.StartPoint, instead of the classic "Curve.PointAtEnd" and "Curve.PointAtStart".

I would say that I'd prefer the Arc way because is more clear and shorter, but it suits well with the concept behind "Curve.PointAt" method.

That's all, I'm using a lot the Arc and Curve classes and I found annoying having to remember those different names for everyone. If I find anything else that could be consolidate I'll tell you.

Thanks in advance.
Cheers.
Ángel.

**Comment by pearswj** [comment]
Hey @angellinares, sorry we never got back to you on this! At the moment we're making a concerted effort to go through the backlog of issues here...

If you want to use a more consistent method naming scheme you could create an [ArcCurve](http://developer.rhino3d.com/api/RhinoCommon/html/T_Rhino_Geometry_ArcCurve.htm) from your Arc (which is derived from the Curve class).

**Comment by angellinares** [comment]
Hi Will,

Thanks for the reply and suggestion. I will do in that way.

I have to recognise that after having some time to explore other softwares
APIs rhinocommon is a piece of cake most of the time in terms of API
structure, documentation and clarity. My wish was trying to push what is
already good to great.

We are planing in moving all the office to Rh6 during next months so I will
have probably more comments (we need to move all our set of tools to Rh6
and double check that they work correctly) in the mid future.

**Comment by pearswj** [comment]
All comments are always appreciated, especially when you're pushing us to be better!

Great to hear that you're rolling out Rhino 6 in the office! Hopefully the migration will be painless, but if you have any questions please do get in touch via [Discourse](http://discourse.mcneel.com/c/rhino-developer).

We're trying to tie up the existing issues in this repository and instead direct developers to Discourse and [YouTrack](http://mcneel.myjetbrains.com) where we're _much_ better at keeping track of conversations.
