### ISSUE TITLE
Misleading name?

### ISSUE THREAD

**Issue by trotil** [mcneel/rhinocommon#172]
I do not understand if this is Rhinocommon source code project we reference while developing plugins for Rhino 5 or it's some old version of OpenNurbs that is just named rhinocommon on github and Rhino3dmIO in solution. Clarification on the readme would help understand the difference. This confusion misled me to believe Rhinocommon we use in rhino plugin development was open sourced.

**Comment by dalefugier** [comment]
You use the RhinoCommon that comes with Rhino 5.

http://developer.rhino3d.com/guides/rhinocommon/

**Comment by trotil** [comment]
Yes Dale, sorry for this submitted issue, I found what I needed indeed. It's an amazing project.
