### ISSUE TITLE
System.TypeInitializationException error while constructing a Plane

### ISSUE THREAD

**Issue by vahidce** [mcneel/rhinocommon#173]
Hi all,

I've added a reference to the lastest version of Rhino3dmIO.dll in a Console Application project and tried to construct a Plane:

`Plane plane = new Plane(Point3d.Origin, Vector3d.YAxis);
`

I'm getting System.TypeInitializationException exception though. Am I missing something big time?

Thanks

**Comment by piac** [comment]
It shouldn't happen. Are you able to look at the inner exception and tell the Description?

Thanks

Giulio
--
Giulio Piacentino
for Robert McNeel & Associates
giulio@mcneel.com

**Comment by vahidce** [comment]
Fortunately, the exception does not happen now that I added the reference again. You can see the exception here. I have also attached the project.

![image](https://cloud.githubusercontent.com/assets/16174905/23772249/91269c80-051a-11e7-9cbe-614f1cb4dd03.png)


[RhinoException.zip](https://github.com/mcneel/rhinocommon/files/832386/RhinoException.zip)

**Comment by piac** [comment]
If this now works, I am going to close this issue, as it really is not something I would know how to fix. Feel free to tell me that this is not fixed, otherwise!
