### ISSUE TITLE
StackOverflowException with Brep.CreatePlanarBreps();

### ISSUE THREAD

**Issue by vahidce** [mcneel/rhinocommon#174]
Hi,

I'm trying to use `Brep.CreatePlanarBreps()` to create Breps from a Curve. It seems that this method has a bug and cause an infinite loop resulting in StackOverflowException. I have tried it with any Curve and the result is the same.

I've downloaded the Rhino3dmIO version 5.1.30000.25 from the Nuget, although when I check in the Properties in VS version is shown as 5.1.30000.14 . I assume that the wrong version is being downloaded from Nuget? 

https://www.nuget.org/packages/Rhino3dmIO.dll-AnyCPU-Windows/5.1.30000.25

Regards,
Vahid

**Comment by dalefugier** [comment]
Hi Vahid,

Brep.CreatePlanarBreps() is not implemented in the standalone Rhino3dmIO toolkit, as the function requires Rhino.
 
If you are trying to use Brep.CreatePlanarBreps() within a RhinoCommon plug-in, then please move this conversation to our Discourse discussion form.

https://discourse.mcneel.com/c/rhino-developer

If you, then please also provide source code that is not working for you.

Thanks,

-- Dale

**Comment by sbaer** [comment]
Brep.CreatePlanarBreps shouldn't even exist in Rhino3dmIo. @acormier may want to take a look at this

**Comment by vahidce** [comment]
Hi Dale,

I was trying it in an standalone application. It was present in Rhino3dmIo library and I assumed that there is a bug in the code.

Thanks
Vahid
