### ISSUE TITLE
File3dm.Read() -> TypeInitializationException\Failed to load library (ErrorCode: 126)

### ISSUE THREAD

**Issue by aireq** [mcneel/rhinocommon#176]
I'm trying to read a 3dm file by calling `Rhino.FileIO.File3dm.Read(filePath)`. However, the call to the `Read()` method is throwing the following exception.

```
System.TypeInitializationException was caught
  HResult=-2146233036
  Message=The type initializer for 'UnsafeNativeMethods' threw an exception.
  Source=Rhino3dmIO
  TypeName=UnsafeNativeMethods
  StackTrace:
       at UnsafeNativeMethods.ONX_Model_ReadFile(String path, IntPtr pStringHolder)
       at Rhino.FileIO.File3dm.Read(String path)
       at SOM.RevitTools.ImportRhino.Command.Execute(ExternalCommandData commandData, String& message, ElementSet elements) in c:\Git\import-rhino\Command.cs:line 50
  InnerException: 
       HResult=-2146233088
       Message=Failed to load library (ErrorCode: 126)
       Source=Rhino3dmIO
       StackTrace:
            at UnsafeNativeMethods.Init()
            at UnsafeNativeMethods..cctor()
       InnerException: 
```

Let me know what additional information would be helpful with troubleshooting this. I'm not sure where to go from here. Thanks!

**Comment by dalefugier** [comment]
@aireq are you calling File3dm.Read from within Rhino, from within a standalone application using the Rhino3dmIO toolkit, or some other way? Can we get a copy of the file you are trying to read? Feel free to email me directly <dale@mcneel.com>.

**Comment by aireq** [comment]
This is from outside of Rhino, but I figured out the problem. I wasn't copying x86\rhino3dmio_native.dll or x64\rhino3dmio_native.dll to the active directly from where my code was running.

**Comment by dalefugier** [comment]
Great, thanks for the update.
