### ISSUE TITLE
IntersectionEvent.ParameterB Property typo

### ISSUE THREAD

**Issue by EmilPoulsen** [mcneel/rhinocommon#179]
I'm assuming this is a typo.. but  in the `IntersectionEvent.ParameterB Property` it says 

> _Gets the parameter on **Curve A** where the intersection occured. If the intersection type is overlap, then this will return the start of the overlap region._

shouldn't that be **Curve B**?

http://developer.rhino3d.com/api/RhinoCommon/html/P_Rhino_Geometry_Intersect_IntersectionEvent_ParameterB.htm

Thanks!
Emil
CORE studio

**Comment by dalefugier** [comment]
Hi @EmilPoulsen, yep definitely a typo. I'll fixed this next time I am in the source code.

Thanks,

-- Dale
