### ISSUE TITLE
Mapping materials to there correct mesh or Brep with C# api.

### ISSUE THREAD

**Issue by blackpandastudios** [mcneel/rhinocommon#187]
I have been successful in loading rhino files directly into Unity (well only Meshes, Breps and Extrusions so far). 

However, I am struggling to find any maps or key-value pairs linking the meshes, breps or extrusions, to any of the materials found in file3dm.AllMaterials.

I have found unique guid's tied to the materials, but am unable to find any material references on any of the file3dm.Objects.

Any pointers?

**Comment by dalefugier** [comment]
The `File3dmObject` has an `Attributes` property that has the index of the material used by the object. You can use this index to find the material in the `File3dmMaterialTable`.

Rhino exports a number of file formats that can be read by Unity (e.g. FBX, OBJ, etc.). Just curious, why don't you just export your model in one of these?

**Comment by blackpandastudios** [comment]
We have 1 click cad software to VR.

I work for InspaceXR, and we have integrations with Revit and support 50+ direct file imports, but we have a demand for direct rhino support.

We would love to be able to have a user simply click import, select the rhino file, and load it into a scene with procedurally optimized visuals and materials to enhance the render quality, currently that works, but it's just coming in flat material currently while I was working out the material mapping. :) 

Another option we were considering, was writing a direct rhino plugin and wrapping the FBX export process from rhino, and using our current FBX>RiverFox workflow. Just additional data like layering, phasing, annotations etc are all things we wish to convert across also, so external integration with 3dm seemed appropriate.

**Comment by blackpandastudios** [comment]
Also, that worked perfectly, was searching all yesterday for a keyword like ID, keymap, etc, just overlooked Attributes :) Lots of useful properties here, I appreciate your support.
