### ISSUE TITLE
wish: linkable, current documentation online

### ISSUE THREAD

**Issue by bengolder** [mcneel/rhinocommon#34]
I know the current SDK documentation generally works, but I just realized that I can't seem to link to specific class, methods or topics, which would be SUPER helpful for discussing rhinocommon issues online. The same goes for any other SDK documentation. I know this would probably be a lot of work to switch over to a different automated documentation system, soo ... I just thought it would be great.

I also know that the most recent docs aren't always here: http://www.rhino3d.com/5/rhinocommon/
It would be great if the rhino3d.com server could automagically point to the most recent build of of the docs.

I'm sure other devs have found some great solutions to automate this.

Thanks for reading, Keep on rocking,

Ben

**Comment by pearswj** [comment]
Latest RhinoCommon API docs are now available at http://developer.rhino3d.com/api/RhinoCommon. It's possible to link directly to [specific elements](http://developer.rhino3d.com/api/RhinoCommon/html/P_Rhino_DocumentEventArgs_Document.htm).

**Comment by maxsu** [comment]
Thanks @pearswj!
