### ISSUE TITLE
Rhino.RhinoApp.Version()

### ISSUE THREAD

**Issue by golsby** [mcneel/rhinocommon#61]
Please add a Version property to Rhino.RhinoApp that returns a System.Version.

Historically, Rhino has based it's revisions on a date rather than a number, so all the calls inside Rhino seem to use CRhinoApp::GetBuildDate(). It probably makes sense to add a function on CRhinoApp to get the Version, and then call it from RhinoCommon.

**Comment by pearswj** [comment]
See http://developer.rhino3d.com/api/RhinoCommon/html/P_Rhino_RhinoApp_Version.htm (available in Rhino 5 and later)
